CREATE TABLE sludinajumi(
    id INT NOT NULL AUTO_INCREMENT,
    lietotaja_id INT NOT NULL,
    vards VARCHAR(255),
    darijuma_veids VARCHAR(255) NOT NULL,
    dzivnieka_veids VARCHAR(255) NOT NULL,
    dzimums BOOLEAN NOT NULL,
    pilseta VARCHAR(255),
    skirne VARCHAR(255),
    apraksts VARCHAR(255),
    datums TIMESTAMP,
    likes_count INT NOT NULL DEFAULT 0,
    attels VARCHAR(255),
    vecums DECIMAL(4, 2),
    CONSTRAINT sludinajumi_pk PRIMARY KEY (id)
);
INSERT INTO sludinajumi
VALUES (
        1,
        3,
        'Xrju',
        'lost',
        'others',
        0,
        'Daugavpils',
        'xrju special',
        'Pazudis xrju special, palidziet atrast!',
        '2023-06-15',
        0,
        'xru.jpg',
        0.25
    ),
    (
        2,
        3,
        'Sofija',
        'adoption',
        'cat',
        1,
        'Daugavpils',
        'bezšķirnes',
        'Melna kaķene meklē mājas. Ļoti pieīlīga.',
        '2023-09-13',
        0,
        'black-cat.jpg',
        1
    ),
    (
        3,
        4,
        'Bilbo',
        'adoption',
        'dog',
        0,
        'Rīga',
        'mopsis',
        'Adopciaji pieejams piemīlīgs mopsis.',
        '2023-10-03',
        0,
        'mopsis.jpg',
        0.9
    ),
    (
        4,
        4,
        'Fredis',
        'adoption',
        'dog',
        0,
        'Rīga',
        'bezsķirnes',
        'Fredis ir ļoti jautrs un dzīvespriecīgs suns. Viņš ātri kļūs par jūsu labāko draugu.',
        '2023-09-24',
        0,
        'fredis.jpg',
        2
    ),
    (
        5,
        5,
        '',
        'adoption',
        'cat',
        0,
        'Ventspils',
        'bezšķirnes',
        'Kākēns ir 3 mēnešus vecs. Nepieciešmas jaunas mājas.',
        '2023-07-19',
        0,
        'kitten.jpg',
        0.25
    ),
    (
        6,
        5,
        '',
        'found',
        'birds',
        0,
        'Ventspils',
        'nezināma',
        'Atrasts papagailis. Ļoti draudzīgs. Īpašnieki, atsaucieties!',
        '2023-10-29',
        0,
        'papagailis.jpg',
        0
    ),
    (
        7,
        6,
        'Jessica',
        'adoption',
        'dog',
        1,
        'Alūksne',
        'extra pūkaina',
        'Ļoti pūkainai suņu meitenei nepieciešama jauna ģimene.',
        '2023-08-03',
        0,
        'jessica.jpg',
        0.8
    );